language: node_js
node_js:
- '0.12'
after_success: npm run report-coverage
deploy:
  provider: npm
  email: d2ltravisdeploy@d2l.com
  api_key:
    secure: Sz2BaecWtquW5zKdHMrAD2XU3BAXBPgzPekhIffW3geEjqOhVTgF6Y1nGrThW7QuU9ue/mKiwlyZ8UXiO89O11oAH7AqSMtKaUXlNfXfoWROdUs/veDEpwvfV9q8nEm8eX487xCLCmlY0wEc6yiuXdeXDNi44R7lpTPTuUBOBd8YRmWhwtcrHO1uwj69onkIUlZzUu8emBLMZqYoQ15ikBUGQoMKSLAVAtmI8haaj5qD7k2bE2t13kpPkWGolx6lFt438c8jpjUXbLRFeXrB2yQXqUuNfR8C049O/Hl2PThQSkzESfljMBZK3ZUMwvHnhiuqp3RN6lXWGSuYQHCLFNyaXeO4odMFhrRCSZQ+aY/OhC3GvounVjYjVQELmM2f6gvzi2b+qmpCXa1580gEyFCPeEHqW50Dvhgwxx/HZstLYPUKzPEwzDfkAXikSqvY3nj7J/kZxb74upQ+KUoDFubaIY98iIWX0tdNJv5nMCpYetJ7m0cd/rvJA38kJ9GKapRXObRL6mc8mr9PMFfszS//PS8olozV9k5jKVe80E7xjBcYCE5oOBfNcbf25SqijS9/ssuhnoTJScTYcOu4voUyc6ZJwQMBkM/SASvX3sqqLc+7n3rnOMQsa6/n4DaSypGynvOxbVRf72d7VUO6+qoAQtq4LbU7G5cvNQUL3BA=
  on:
    tags: true
    all_branches: true
    repo: Brightspace/frau-appconfig-builder
